[tool.poetry]
name = "phasenet-pytorch"
version = "0.0.1"
description = "PyTorch adaption of PhaseNet"
authors = [
    "Ziyi Xi <ziyixi@mail.ustc.edu.cn>",
    "Weiqiang Zhu <wayne.weiqiang@gmail.com>",
]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.9"
torch = "^1.13.1"
torchvision = "^0.14.1"
torchaudio = "^0.13.1"
hydra-core = "^1.3.1"
omegaconf = "^2.3.0"
pyasdf = "^0.7.5"
obspy = "^1.4.0"
tqdm = "^4.64.1"
matplotlib = "^3.6.3"
numpy = "^1.24.1"
pytorch-lightning = "^1.9.0"
torchmetrics = "^0.11.0"
scipy = "^1.10.0"
hydra-submitit-launcher = "^1.2.0"
hydra-optuna-sweeper = "^1.2.0"
segmentation-models-pytorch = "^0.3.2"
wandb = "^0.13.9"
sqlalchemy = "<2.0"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.10"
autopep8 = "^2.0.1"
click = "^8.1.3"
loguru = "^0.6.0"
pandas = "^1.5.3"
ipykernel = "^6.20.2"
itables = "^1.4.5"
seaborn = "^0.12.2"
ipywidgets = "^8.0.4"
h5py = "^3.8.0"
mpi4py = "^3.1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"