[tool.poetry]
name = "phasenet-pytorch"
version = "0.0.1"
description = "PyTorch adaption of PhaseNet"
authors = [
    "Ziyi Xi <ziyixi@mail.ustc.edu.cn>",
    "Weiqiang Zhu <wayne.weiqiang@gmail.com>",
]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.9"
torch = "^1.13.0"
torchvision = "^0.14.0"
torchaudio = "^0.13.0"
hydra-core = "^1.2.0"
omegaconf = "^2.2.3"
pyasdf = "^0.7.5"
obspy = "^1.4.0"
tqdm = "^4.64.1"
matplotlib = "^3.6.2"
numpy = "^1.23.5"
tensorboard = "^2.11.0"
pytorch-lightning = "^1.8.3-post.1"
torchmetrics = "^0.10.3"
scipy = "^1.9.3"
hydra-submitit-launcher = "^1.2.0"
hydra-optuna-sweeper = "^1.2.0"
segmentation-models-pytorch = "^0.3.0"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.6"
autopep8 = "^2.0.0"
Sphinx = "^5.3.0"
rstcheck = "^6.1.1"
click = "^8.1.3"
loguru = "^0.6.0"
pandas = "^1.5.2"
torch-tb-profiler = "^0.4.0"
ipykernel = "^6.18.1"
itables = "^1.3.5"
seaborn = "^0.12.1"
ipywidgets = "^8.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
