[tool.poetry]
name = "phasenet-pytorch"
version = "0.1.0"
description = "PyTorch adaption of PhaseNet"
authors = ["ziyi xi <ziyixi@mail.ustc.edu.cn>"]
license = "MIT"
readme = "README.md"
packages = [{include = "phasenet_pytorch"}]

[[tool.poetry.source]]
name = "torch_nightly"
url = "https://download.pytorch.org/whl/nightly/cu117"
secondary = true

[tool.poetry.dependencies]
python = "<3.12,>=3.9"
torch = { version = "^2.0.0.dev0", allow-prereleases = true, source = "torch_nightly", platform = 'linux'}
torchvision = { version = "^0.15.0.dev0", allow-prereleases = true, source = "torch_nightly", platform = 'linux'}
torchaudio = { version = "^2.0.0.dev0", allow-prereleases = true, source = "torch_nightly", platform = 'linux'}
pytorch-lightning = "^1.9.0"
hydra-core = "^1.3.1"
omegaconf = "^2.3.0"
pyasdf = "^0.7.5"
obspy = "^1.4.0"
tqdm = "^4.64.1"
matplotlib = "^3.6.3"
numpy = "^1.24.1"
torchmetrics = "^0.11.0"
scipy = "^1.10.0"
hydra-submitit-launcher = "^1.2.0"
segmentation-models-pytorch = "^0.3.2"
wandb = "^0.13.9"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.10"
autopep8 = "^2.0.1"
sphinx = "^6.1.3"
rstcheck = "^6.1.1"
click = "^8.1.3"
loguru = "^0.6.0"
pandas = "^1.5.3"
ipykernel = "^6.20.2"
itables = "^1.4.5"
seaborn = "^0.12.2"
ipywidgets = "^8.0.4"
h5py = "^3.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
