[tool.poetry]
name = "phasenet-pytorch"
version = "0.0.1"
description = "PyTorch adaption of PhaseNet"
authors = [
    "Ziyi Xi <ziyixi@mail.ustc.edu.cn>",
    "Weiqiang Zhu <wayne.weiqiang@gmail.com>",
]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.9"
torch = {version="^1.12.0"}
torchvision = {version="^0.13.0"}
torchaudio = {version="^0.12.0"}
hydra-core = "^1.2.0"
omegaconf = "^2.2.0"
pyasdf = "^0.7.5"
obspy = "^1.3.0"
tqdm = "^4.64.0"
matplotlib = "^3.5.1"
numpy = "^1.22.3"
tensorboard = "^2.8.0"
pytorch-lightning = "^1.7.0"
torchmetrics = "^0.9.3"
scipy = "^1.9.0"
hydra-submitit-launcher = "^1.2.0"
hydra-optuna-sweeper = "^1.2.0"

[tool.poetry.group.dev.dependencies]
pylint = "^2.13.7"
autopep8 = "^1.6.0"
Sphinx = "^4.5.0"
rstcheck = "^5.0.0"
click = "^8.1.2"
loguru = "^0.6.0"
pandas = "^1.4.2"
torch-tb-profiler = "^0.4.0"
ipykernel = "^6.15.2"
itables = "^1.2.0"
seaborn = "^0.11.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
