# @package _global_
data:
  data_dir: /mnt/home/xiziyi/Packages_Research/PhaseNet-PyTorch/dataset-coverall-20221124
  train: tongaml_train.h5
  test: tongaml_test.h5
  val: tongaml_val.h5
  train_trans: ["shift", "scale", "label"]
  val_trans: ["scale", "label"]
  test_trans: ["scale", "label"]

  # tuned
  stack_ratio: 0.9738217746076991
  noise_replace_ratio: 0.3210340323794437

train:
  epochs: 160

  accelerator: gpu
  strategy: ddp_find_unused_parameters_false
  use_amp: false
  use_a100: false

  distributed_devices: [0, 1, 2, 3]
  # distributed_devices: [0]

  run_type: train

  deterministic: false

  step_lr_gamma: 0.6
  learning_rate: 0.001

model:
  nn_model: deeplabv3+
  deeplab_encoder_weights: imagenet

spectrogram:
  mean: [130.9636, 136.6858,  97.8700]
  std: [362.7432, 374.5648, 296.8759]

visualize:
  log_val: false
  log_test: false
  log_epoch: 30
  sgram_threshold: 500 
  log_test_seprate_folder: false
  log_test_seprate_folder_path: ""

hydra:
  job:
    # name: test_deeplab
    name: baseline20221124
  launcher:
    timeout_min: 239
    nodes: 1
    tasks_per_node: 4
    cpus_per_task: 4
    mem_gb: 100
    gres: gpu:v100:4
    account: cmse