# @package _global_
data:
  data_dir: /Users/ziyixi/Library/CloudStorage/OneDrive-MichiganStateUniversity/Packages_Research/PhaseNet-PyTorch/dataset_updated_psfreq
  train: tongaml_train.h5
  test: tongaml_test.h5
  val: tongaml_val.h5

  train_batch_size: 4
  val_batch_size: 1
  test_batch_size: 1
  train_shuffle: false

  train_trans: ["shift", "scale", "label"]
  val_trans: ["scale", "label"]
  test_trans: ["scale", "label"]

train:
  epochs: 3

  limit_train_batches: 2
  limit_val_batches: 8
  limit_test_batches: 8

  loss_func: kl_div

  ckpt_path: /Users/ziyixi/Library/CloudStorage/OneDrive-MichiganStateUniversity/Packages_Research/PhaseNet-PyTorch/temp/epoch=143-loss_val=179.88.ckpt

visualize:
  example_num: 8

  log_train: false
  log_val: false
  log_test: true

  log_epoch: 2
  sgram_threshold: 500

  log_test_seprate_folder: true
  log_test_seprate_folder_path: /Users/ziyixi/Library/CloudStorage/OneDrive-MichiganStateUniversity/Packages_Research/PhaseNet-PyTorch/figs/test_snr

  plot_waveform_based_on: "PS"

postprocess:
  save_test_step_to_disk: false
  test_step_save_path: /Users/ziyixi/Library/CloudStorage/OneDrive-MichiganStateUniversity/Packages_Research/PhaseNet-PyTorch/dump

hydra:
  job:
    name: test_fig
