hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
defaults:
  - base_config
  - data: local
  - spectrogram: local
  - model: local
  - train: local
  - visualize: local
  - _self_
