hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
defaults:
  - base_config
  - data: local
  - spectrogram: local
  - model: sample
  - train: local
  - profile: sample
  - visualize: local
  - _self_
