# @package _global_
data:
  data_dir: /mnt/home/xiziyi/Packages_Research/PhaseNet-PyTorch/dataset-coverall-20221124
  train: tongaml_train.h5
  test: tongaml_test.h5
  val: tongaml_val.h5

  train_batch_size: 2
  train_shuffle: false

train:
  epochs: 3
  limit_train_batches: 2
  limit_val_batches: 2
  limit_test_batches: 2

visualize:
  example_num: 2
  log_train: true
  log_val: true
  log_test: true

wandb:
  # job_name: baseline
  job_name: test
  # project_name: PhaseNet-TF
  project_name: PhaseNet-TF-Test

hydra:
  job:
    name: test
