# @package _global_
data:
  data_dir: /mnt/home/xiziyi/Packages_Research/PhaseNet-PyTorch/dataset-coverall-20221124
  train: tongaml_train.h5
  test: tongaml_test.h5
  val: tongaml_val.h5

  train_batch_size: 2
  train_shuffle: false

train:
  epochs: 3
  limit_train_batches: 2
  limit_val_batches: 2
  limit_test_batches: 2

visualize:
  log_train: false
  log_val: false
  log_test: false

hydra:
  job:
    name: test
